const $=s=>document.querySelector(s), content=$('#content'), search=$('#search');let view='dashboard',familyFilter='All',query='';
const families=[...new Set(ENGINES.map(e=>e.family))];
function setHead(t,s){$('#pageTitle').textContent=t;$('#pageSub').textContent=s}
function card(e){return `<article class="engine-card" data-engine="${e.id}"><div class="engine-top"><span class="engine-code">${e.code}</span><span class="pill">${e.family}</span></div><div class="meta">${e.displacement} · ${e.configuration} · ${e.fuel}</div><div class="cars">${e.cars.slice(0,4).join(' · ')}</div></article>`}
function filtered(){return ENGINES.filter(e=>(familyFilter==='All'||e.family===familyFilter)&&(!query||[e.code,e.family,e.fuel,e.configuration,e.status,...e.cars].join(' ').toLowerCase().includes(query)))}
function dashboard(){setHead('Engine Intelligence','Browse Toyota engine families, applications and sourcing context.');const active=ENGINES.filter(e=>/Active/.test(e.status)).length,hybrid=ENGINES.filter(e=>e.fuel==='Hybrid').length,diesel=ENGINES.filter(e=>e.fuel==='Diesel').length;content.innerHTML=`<div class="stats"><div class="stat"><strong>${ENGINES.length}</strong><span>Engines tracked</span></div><div class="stat"><strong>${families.length}</strong><span>Families</span></div><div class="stat"><strong>${active}</strong><span>Active variants</span></div><div class="stat"><strong>${diesel} / ${hybrid}</strong><span>Diesel / hybrid</span></div></div><section class="panel"><div class="panel-head"><div><h2>Engine families</h2><p>Use families to understand architecture and sourcing segments.</p></div></div><div class="family-grid">${families.map(f=>`<button class="family-card" data-family="${f}"><b>${f}</b><small>${ENGINES.filter(e=>e.family===f).length} engines</small></button>`).join('')}</div></section><section class="panel"><div class="panel-head"><div><h2>Commercially useful examples</h2><p>Mix of high-volume, 4x4/diesel and newer-generation engines.</p></div></div><div class="engine-grid">${['2GR-FE','2AR-FE','2ZR-FE','1GR-FE','1KD-FTV','1GD-FTV'].map(c=>card(ENGINES.find(e=>e.code===c))).join('')}</div></section>`;bind()}
function familyView(f){familyFilter=f;view='engines';render()}
function familiesView(){setHead('Engine Families','Compare the engine families before drilling into individual variants.');content.innerHTML=`<section class="panel"><div class="family-grid">${families.map(f=>`<button class="family-card" data-family="${f}"><b>${f}</b><small>${ENGINES.filter(e=>e.family===f).length} engines</small><small>${FAMILY_NOTES[f]||'Toyota engine family group.'}</small></button>`).join('')}</div></section>`;bind()}
function enginesView(){setHead('All Engines','Search and filter the master engine list.');const rows=filtered();content.innerHTML=`<div class="filters"><button class="filter ${familyFilter==='All'?'active':''}" data-filter="All">All</button>${families.map(f=>`<button class="filter ${familyFilter===f?'active':''}" data-filter="${f}">${f}</button>`).join('')}</div>${rows.length?`<div class="engine-grid">${rows.map(card).join('')}</div>`:'<div class="empty">No engines match this search.</div>'}`;bind()}
function detail(id){const e=ENGINES.find(x=>x.id==id);setHead(e.code,`${e.family} family · ${e.displacement} ${e.configuration}`);content.innerHTML=`<button class="detail-back" id="back">← Back to engines</button><div class="hero"><section class="panel"><h2 class="detail-title">${e.code}</h2><div class="detail-family">Toyota ${e.family} family</div><div class="specs"><div class="spec"><small>Displacement</small><b>${e.displacement}</b></div><div class="spec"><small>Configuration</small><b>${e.configuration}</b></div><div class="spec"><small>Fuel</small><b>${e.fuel}</b></div><div class="spec"><small>Status</small><b>${e.status}</b></div></div></section><section class="panel"><h2>Why this family matters</h2><p class="sourcing">${FAMILY_NOTES[e.family]||'Track this family as a distinct sourcing category. Vehicle application, market, year and exact variant should be verified before purchase.'}</p></section></div><section class="panel"><h2>Typical vehicle applications</h2><p>These are useful donor-model search terms. Exact compatibility depends on year, market and specification.</p><div class="vehicle-list">${e.cars.map(c=>`<span class="vehicle">${c}</span>`).join('')}</div></section><section class="panel"><h2>Next commercial data to attach</h2><p>Supplier country · wholesale purchase price · mileage · test status · freight per unit · landed cost · destination price · gross margin · inventory velocity.</p></section>`;$('#back').onclick=()=>{view='engines';render()}}
function bind(){document.querySelectorAll('[data-family]').forEach(x=>x.onclick=()=>familyView(x.dataset.family));document.querySelectorAll('[data-filter]').forEach(x=>x.onclick=()=>{familyFilter=x.dataset.filter;enginesView()});document.querySelectorAll('[data-engine]').forEach(x=>x.onclick=()=>detail(x.dataset.engine))}
function render(){document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view));if(view==='dashboard')dashboard();else if(view==='families')familiesView();else enginesView()}
document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>{view=n.dataset.view;familyFilter='All';render()});search.addEventListener('input',e=>{query=e.target.value.toLowerCase().trim();if(query){view='engines';familyFilter='All'}render()});render();
